name: Setup
description: Common environment setup

runs:
  using: composite
  steps:
    - name: "Install Pnpm"
      uses: "pnpm/action-setup@v4"
      with:
        version: "8"
    - uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        node-version: 20.x
    - uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: npm-v3-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: "pnpm install"
      shell: bash