
= Finance

[.readme-notice]
NOTE: This document is better viewed at https://docs.openzeppelin.com/confidential-contracts/api#finance

This directory includes primitives for on-chain confidential financial systems:

- {VestingWalletConfidential}: Handles the vesting of confidential tokens for a given beneficiary. Custody of multiple tokens can be given to this contract, which will release the token to the beneficiary following a given, customizable, vesting schedule.
- {VestingWalletCliffConfidential}: Variant of {VestingWalletConfidential} which adds a cliff period to the vesting schedule.

For convenience, this directory also includes:

- {VestingWalletCliffExecutorConfidential}: A Default implementation of `VestingWalletConfidential` which implements both `VestingWalletCliffConfidential` and execution via {ERC7821WithExecutor}.
- {VestingWalletCliffExecutorConfidentialFactory}: A factory which allows creating `VestingWalletCliffExecutorConfidential` in batch.


== Contracts
{{VestingWalletConfidential}}
{{VestingWalletCliffConfidential}}
{{VestingWalletCliffExecutorConfidentialFactory}}
{{VestingWalletCliffExecutorConfidential}}
{{ERC7821WithExecutor}}
